### ISSUE TITLE
tipLocation "above" doesn't work

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/clark-tooltip#2]
The following renders a tooltip:
`<span tip="{{ tips.OUTCOMES_FROM_OTHER_SOURCES }}" tipLocation="side">?</span>`
however, this does not:
`<span tip="{{ tips.OUTCOMES_FROM_OTHER_SOURCES }}" tipLocation="above">?</span>`

**Comment by tylernhoward** [comment]
Leaving this open until verified that issue is fixed
